version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    reviewers:
      - 'DevExpress/devextreme-devops'

  - package-ecosystem: 'npm'
    directory: '/packages/devextreme-react/'
    schedule:
      interval: 'weekly'
    reviewers:
      - 'DevExpress/devextreme-devops'

  - package-ecosystem: 'npm'
    directory: '/packages/devextreme-react-generator/'
    schedule:
      interval: 'weekly'
    reviewers:
      - 'DevExpress/devextreme-devops'

  - package-ecosystem: 'npm'
    directory: '/packages/sandbox/'
    schedule:
      interval: 'weekly'
    reviewers:
      - 'DevExpress/devextreme-devops'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    reviewers:
      - 'DevExpress/devextreme-devops'
