name: Continuous Integration
on:

  push:
    branches:
    - master

  pull_request:
    branches:
    - master
  
env:
  nodeVersion: 12.x

jobs:

  test:
    runs-on: windows-latest
    name: Build and run tests
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.nodeVersion }}

    - name: Install package dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Test
      run: npm test