name: Guard - Up version generator if sourcies files changed 

on:
  push:
    branches:
    - master
    - '[12][0-9].[12]'
  pull_request:
    branches:
      - '**'

jobs:
  guard:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Get sources
      uses: actions/checkout@v2

    - name: Get changed files
      id: changed
      uses: tj-actions/changed-files@v29.0.2

    - name: Check changes
      if: ${{ contains(steps.changed.outputs.all_changed_files, 'devextreme-react-generator/src/') && !contains(steps.changed.outputs.all_changed_files, 'devextreme-react-generator/package.json') }}
      run: |
        echo "Please update version in packages/devextreme-react-generator/package.json"
        exit 1
