name: Tests

on:
  push:
    branches:
    - master
    - '[12][0-9].[12]'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Get sources
      uses: actions/checkout@v2

    - name: Clone devextreme repo from PR author fork
      continue-on-error: true
      if: github.event_name == 'pull_request'
      run: git clone -b ${{github.event.pull_request.head.ref}} https://github.com/${{github.event.pull_request.user.login}}/devextreme ../devextreme

    - name: Clone devextreme repo
      run: test -d ../devextreme || git clone -b 23_2 https://github.com/devexpress/devextreme ../devextreme

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install packages in devextreme repo
      working-directory: ../devextreme
      run: npm i --no-audit --no-fund

    - name: Build devextreme repo
      working-directory: ../devextreme
      run: npm run build-npm-devextreme

    - name: Install devextreme package
      run: |
        npm i --save-dev ../devextreme/artifacts/npm/devextreme/ --workspace=devextreme-react --workspace=devextreme-react-sandbox

    - name: Run npm install
      run: npm install --no-audit --no-fund

    - name: Run devextreme-react-generator tests
      run: npm run test --workspace=devextreme-react-generator

    - name: Run lint
      run: npm run lint

    - name: Pack with React
      run: npm run pack

    - name: Run tests with React
      run: npm run test

    - name: Archive internal-tools artifacts
      uses: actions/upload-artifact@v3
      with:
        name: internal-tools-artifacts
        path: artifacts/internal-tools/
        retention-days: 7
