name: Tests

on:
  push:
    branches:
    - master
    - '[12][0-9].[12]'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Get sources
      uses: actions/checkout@v2

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Restore devextreme
      run: npm run restore-devextreme

    - name: Run npm install
      run: npm install --no-audit --no-fund

    - name: Run devextreme-react-generator tests
      run: npx lerna run --scope devextreme-react-generator test

    - name: Run bootstrap
      run: npm run bootstrap

    - name: Run lint
      run: npm run lint

    - name: Pack with React
      run: npm run pack

    - name: Run tests with React
      run: npm run test

    - name: Archive internal-tools artifacts
      uses: actions/upload-artifact@v3
      with:
        name: internal-tools-artifacts
        path: artifacts/internal-tools/
        retention-days: 7
