name: Tests

on:
  push:
    branches:
    - master
    - '[12][0-9].[12]'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Get sources
      uses: actions/checkout@v2

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Restore devextreme
      run: npm run restore-devextreme

    - name: Run npm install
      run: npm install --no-audit --no-fund

    - name: Run devextreme-react-generator tests
      run: npx lerna run --scope devextreme-react-generator test

    - name: Run build
      env:
        NODE_OPTIONS: "--max-old-space-size=4096"
      run: npm run build

    - name: Run tests with React
      run: npm run test

    - name: Check generated code
      shell: bash
      run: |
        git add . -N
        changes=$(git diff --name-status HEAD -- packages/devextreme-react/src)
        if [ -n "$changes" ]; then
          echo "Generated code is outdated. The following files have uncommitted changes:"
          echo "$changes";
          echo "To update generated code, generate metadata, build packages and commit changes."
          exit 1
        fi

    - name: Pack with React
      run: npm run pack

    - name: Archive internal-tools artifacts
      uses: actions/upload-artifact@v3
      with:
        name: internal-tools-artifacts
        path: artifacts/internal-tools/
        retention-days: 7
